title: Distinct roles of Atf3, Zfp711 and Bcl6b in early embryonic hematopoietic and endothelial lineage specification
description: Manuscript-Support Page for Cetin et al. (2025) Development
theme: jekyll-theme-cayman
author: Ridvan Cetin
baseurl: "/CMO_Atf3_Zfp711_Bcl6b"
url: "https://ridvan-cetin.github.io"

# Optional configurations
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from build
exclude:
  - Organized/
  - Original_code/
  - FlowCytometricAnalysis_data/
