title: Distinct roles of Atf3, Zfp711 and Bcl6b in early embryonic hematopoietic and endothelial lineage specification
description: Manuscript-Support Page
theme: jekyll-theme-cayman
author: Ridvan Cetin
baseurl: "/CMO_Atf3_Zfp711_Bcl6b/support_site/" # Set this to the subdirectory of your site
url: "https://ridvan-cetin.github.io" # Do not include the subdirectory here

# Optional configurations
markdown: kramdown
plugins:
  - jekyll-feed
